name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
env:
  cloud: google-cloud
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: my test
        run: mvn test
